apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: build-rpi-container-image-builder
resources:
- namespace.yaml
- job.yaml

commonLabels:
  app: build-rpi-container-image-builder

configMapGenerator:
- name: sources
  files:
  - Dockerfile

secretGenerator:
- name: repository-auth-secrets
  files:
  - auth.json
